FROM php:8.4-fpm-alpine

ARG UID=1001
ARG GID=1001

RUN apk add --no-cache git bash curl unzip libpng-dev libxml2-dev oniguruma-dev nodejs npm

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/html

# Non-root user
RUN addgroup -g ${GID} -S laravel \
    && adduser -u ${UID} -G laravel -S laravel

USER laravel

CMD ["php-fpm"]
